language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.5.10 MIGRATE='true'
  - DJANGO=1.6.10 MIGRATE='true'
  - DJANGO=1.7.7 MIGRATE='./manage.py migrate'
  - DJANGO=1.8 MIGRATE='./manage.py migrate'

install:
  - pip install -q Django==$DJANGO
  - pip install pyquery
  - python setup.py -q install
  - npm install -g grunt-cli
  - pushd . ; cd client && npm install; popd

branches:
  only:
    - master

matrix:
  exclude:
  - python: 3.3
    env: DJANGO=1.5.10 MIGRATE='true'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - pushd . && cd client && grunt travis-ci && popd
 - pushd . && cd examples && $MIGRATE && ./manage.py test server && popd
